### ISSUE TITLE
我安装了.NET6.0 启动时仍然提示需要安装.NET

### ISSUE THREAD

**Issue by CharWong** [Mythologyli/iOSFakeRun#13]
![image](https://user-images.githubusercontent.com/26594777/203458816-4798b3f8-41eb-4d2e-895e-e94324173537.png)
![image](https://user-images.githubusercontent.com/26594777/203458839-59ff5d12-dc86-4459-84ee-6e6ca9671a02.png)

**Comment by Mythologyli** [comment]
安装的是 .NET Desktop Runtime 吗
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.11-windows-x64-installer

**Comment by CharWong** [comment]
是的，一开始安装的是这个（也就是上图对话框点击“是”之后自动跳出来的链接的版本），安装后继续跳出这个对话框。
我按照提示从本项目readme文档的连接去找到6.0.0版本安装后，未提示报错，但是双击后没有反应。
然后点击你刚才的这个连接覆盖安装后，就可以了（挠头

总只能用了
