### ISSUE TITLE
 DeveloperDiskImage不更新了吗

### ISSUE THREAD

**Issue by Ptuer-swpu** [Mythologyli/iOSFakeRun#14]
有设备升级到16.3了，作者快更新

**Comment by Mythologyli** [comment]
你自己去找不就行了，我还不是要去别处找，我又不能把镜像变出来

自己不会找，伸手的时候麻烦态度好一点

**Comment by Mythologyli** [comment]
https://github.com/Mythologyli/DeveloperDiskImage

找不到 16.3 的，16.4 的放进去了，你把 16.4 或者 16.1 的改名为 16.3 看看能不能用

**Comment by freeze-dolphin** [comment]
请问一下这个开发者镜像的来源是什么

社区大佬自己编写的吗，还是官方有发布的地方？

**Comment by wouiSB** [comment]
@freeze-dolphin 应该是别人从xcode里提取的吧
