### ISSUE TITLE
显示目前无法访问smartscreen以及该处理器类型不支持该安装包 是华为电脑的问题吗

### ISSUE THREAD

**Issue by noname0331** [Mythologyli/iOSFakeRun#19]
安装网络上提供的解决办法好像都无法解决 请问是华为电脑的问题吗

**Comment by Geniucker** [comment]
smartscreen是微软的一个建议到杀毒插件，用于拦截你网上下下来的危险应用，如果你信任这个应用可以无视并选择放行，另一个问题要不给个截图？

**Comment by noname0331** [comment]
![AED6CD2F-EC11-4785-8BA9-C73EF60428E6](https://user-images.githubusercontent.com/130959239/232401429-ca837662-e3d5-44ea-b14a-674072223d26.jpeg)

**Comment by Geniucker** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
我猜你是ARM架构的处理器，你可以在这里下载对应版本的.NET环境
当然如果你懒得弄并且刚好装过Python的话你也可以看看这个/doge
https://github.com/Geniucker/iOSRealRun-cli

**Comment by noname0331** [comment]
问题解决了！非常感谢
