### ISSUE TITLE
求问16.3怎么操作

### ISSUE THREAD

**Issue by huiliyi-XJ** [Mythologyli/iOSFakeRun#20]
请问16.3的系统没有镜像怎么用捏？我前两天还是可以的，今天突然无法连接，说是没有16.3的镜像wuwuwu

**Comment by Geniucker** [comment]
请再读一遍readme，里面有说怎么办

**Comment by huiliyi-XJ** [comment]
> 你好，我已近重新读过readme了，按照要求一步步来的，但是早上提示的没有16.3镜像还是不知道怎么解决QAQ，不过现在又可以连接上了

**Comment by Mythologyli** [comment]
已支持 16.4 16.5
https://github.com/Mythologyli/iOSFakeRun/releases/tag/v0.8

**Comment by huiliyi-XJ** [comment]
> 

谢谢作者！现在升级到16.7已经可以了！
