### ISSUE TITLE
ios 16.6

### ISSUE THREAD

**Issue by geniusleung** [Mythologyli/iOSFakeRun#25]
Can you add support for ios 16.6? Thank you

**Comment by geniusleung** [comment]
Hi, can you also add a feature that can add a start from spot? thanks

**Comment by Ptuer-swpu** [comment]
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases，16.6 in this

**Comment by Mythologyli** [comment]
See https://github.com/Mythologyli/iOSFakeRun/releases
