### ISSUE TITLE
15.7开发者镜像请求

### ISSUE THREAD

**Issue by ZouJoelin** [Mythologyli/iOSFakeRun#7]
作者你好，我手机系统是15.7的，机子也有点旧了暂时不打算升级iOS16，方便给个15.7的镜像嘛？

**Comment by Mythologyli** [comment]
https://github.com/pdso/DeveloperDiskImage

**Comment by cy2272069717** [comment]
作者大大，能不能给个15.8的镜像啊，旧手机升不了也降不回去……
