### ISSUE TITLE
16.1文件

### ISSUE THREAD

**Issue by sheng021108** [Mythologyli/iOSFakeRun#8]
16.1文件为什么是这个东西：攣ͼ㾮ﾠ伖淚汗侮ॱ暗㵎턁悑ꢯϡ�話꫇秩҇￐膛꽦쉀鈈庽ӌ촜瑧參愱䓒䤧郁�檃ﶚ쓜㉀떛愒蒜停쥹繒疀爲스᷏冂Ɨ㰚냦脴퇥퓤

**Comment by Mythologyli** [comment]
可以截张图看看吗，我没发现异常
![image](https://user-images.githubusercontent.com/15955880/198831899-7fed1a76-53f6-4ded-acce-8d6f9cf06cd5.png)

**Comment by sheng021108** [comment]
![Uploading H(LX1B`@$NV{O$4MVTI~T4K.png…]()

**Comment by Mythologyli** [comment]
你的图片好像上传失败了？

**Comment by sheng021108** [comment]
![H(LX1B`@$NV{O$4MVTI~T4K](https://user-images.githubusercontent.com/115602174/198832059-b1bff7e9-7688-4948-afe5-dabcae455f9e.png)

**Comment by sheng021108** [comment]
我还想反馈一个问题：我是ios16.0的，今天连接的时候显示未安装16.0的镜像，我去看，结果之前下载的文件没了。我又去库里下载，再放进去，还是不行

**Comment by Mythologyli** [comment]
本来就不是文本文件，所以显示乱码也是正常的吧

**Comment by Mythologyli** [comment]
> 我还想反馈一个问题：我是ios16.0的，今天连接的时候显示未安装16.0的镜像，我去看，结果之前下载的文件没了。我又去库里下载，再放进去，还是不行

为啥没了，你用新版本覆盖了？还是神秘消失了。
如果下载镜像有困难的话，你可以去 Release 里下载那个最大的压缩包使用，那个镜像是全的。
